# General application configuration
replicaCount: 1

image:
  repository: foxlifes/pb-app
  pullPolicy: Always
  tag: "latest"

service:
  enabled: true
  type: ClusterIP
  port: 80

ingress:
  enabled: false
  className: "nginx"
  annotations: {}
  hosts:
    - host: yourapp.local
      paths:
        - path: /
          pathType: Prefix
  tls: []

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}

# ServiceAccount configuration
serviceAccount:
  create: true
  name: ""
  annotations:  # Optional annotations
    example.annotation/key: "value"

# Autoscaling configuration
autoscaling:
  enabled: true  # Set to true to enable autoscaling, false to disable
  minReplicas: 1  # Minimum number of replicas
  maxReplicas: 10 # Maximum number of replicas
  targetCPUUtilizationPercentage: 80  # Target CPU utilization percentage
  targetMemoryUtilizationPercentage: 75  # Target Memory utilization percentage
