apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "pb-app.fullname" . }}  # Use pb-app.fullname to get the full name
  labels:
    {{- include "pb-app.labels" . | nindent 4 }}  # Include common labels
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "pb-app.name" . }}  # Use pb-app.name for the app label
  template:
    metadata:
      labels:
        app: {{ include "pb-app.name" . }}  # Again, use pb-app.name
    spec:
      containers:
        - name: {{ include "pb-app.name" . }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          ports:
            - containerPort: 80
